version: '3'

services:

  auth-service:
    build: ./user-microservice
    container_name: auth-service
    ports:
      - "7000:7000"
    depends_on:
      - mongo
    networks:
      - my-network

  product-microservice:
    build: ./product-microservice
    container_name: product-microservice
    depends_on:
      - mongo
      - rabbitmq
    environment:
      - PORT_ONE=7100
      - MONGO_URI=mongodb://mongo:27017
      - RABBITMQ_URI=amqp://rabbitmq:5672
    ports:
      - "7100:7100"
    networks:
      - my-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - my-network

networks:
  my-network:
    driver: bridge