version: '3'

services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
